version: "3.3"
services:
  frontend:
    restart: always
    image: frontend:latest
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_WEBSOCKET_SERVER_URL=http://localhost:4000
      - NEXT_PUBLIC_GRAPHQL_URL_CLIENT=http://localhost:4000/graphql
      - NEXT_PUBLIC_PAGE_SIZE=8
      - GRAPHQL_URL_SSR=http://backend:4000/graphql

  backend:
    restart: always
    image: backend:latest
    ports:
      - "4000:4000"
    environment:
      - MONGODB_CONNECTION=mongodb+srv://testuser:testpass@cluster0.ex1fq.mongodb.net/taskdb?retryWrites=true&w=majority
      - FAKER_INTERVAL_MIN=2
      - PAGE_SIZE=8
      - CORS_ORIGIN=http://localhost:3000
      - COIN_API_HOSTNAME=rest.coinapi.io
      - COIN_API_PATH=/v1/exchangerate/
      - COIN_API_KEY=B951CEAB-0BE1-4991-AE0F-38491B0A785D
