import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <button className="px-4 py-2 font-bold text-white bg-blue-500 rounded hover:bg-blue-700">
        Button
      </button>
    </>
  );
}
